POST http://localhost:3003/api/blogs
Content-Type: application/json

{ "title": "The Cat in the Hat 2",
      "userId": "5f611794f427ff74350da53d",
      "url":
       "https://www.storyjumper.com/book/read/44442296/The-Cat-in-the-Hat#page/1",
      "likes": 500 }
